config/routes.rb
Rails.application.routes.draw do

    # - from rails g scaffold
  resources :contacts

    # - configuring after generating DEVISE's controllers 
  devise_for :users, controllers: { sessions: 'users/sessions' }

    # - setting DEVISE's login/Register view as root
  devise_scope :user do 
    root to: "users/sessions#new"
  end

    # - soft delete
    # - user clicks check box at app/views/contacts/index
    # - User.deactivate toggled true/false
    # - User.deactivated = true 
    #   + displayed in side bar
  post '/deactivate_contact' => 'contacts#deactivate_contact'
  post '/reactivate_contact' => 'contacts#reactivate_contact'

    # - search box at: views/contacts/index.html.erb
    # - user types search string
    # - list of matching Contacts is displayed
  post 'search_contacts' => 'contacts#search_contacts'

end

app/views/shared/_csv_button.html.erb
<%= link_to 'Csv', contact_path(id, format: "csv") %>

app/views/shared/_deactivated_contact.html.erb
<!-- 
###########

- rendered in app/views/contacts/index.html.erb next 

- gets it's data passed from ContactsController#index

- displays Contacts.deactivate = true (attribute default false)

- Contact.deactivate set by user in app/views/contacts/index.html.erb via form
  post to ContactsController#deactivate_contact

##########
-->

<li>
  <%= deactivated_contact.name %>
</li>
<span>
  <%= check_box_tag "show[]", "#{deactivated_contact.id}" %>
  <%= label_tag "show" %>
</span>

app/views/shared/_session_state.html.erb
<!-- 
###########
  - render in views/layouts/application.html.erb
  - displays a logout button user logged in
##########
-->

<div class="navClass">

  <% if user_signed_in? %>

  <h3>Currently logged in: <%= current_user.email %></h3>

    <button class="btn-lk btn-md newPostBtn">
      <%= link_to('logout', destroy_user_session_path, method: :delete) %>
    </button>

    <button class="btn-lk btn-md newPostBtn">
      <%= link_to('edit', edit_user_registration_path, method: :get) %>
    </button>

    <button class="btn-lk btn-md newPostBtn">
      <%= link_to('home', root_path, method: :get) %>
    </button>    

 <% end %>

</div>