config/routes.rb
Rails.application.routes.draw do

    # - from rails g scaffold
  resources :contacts

    # - configuring after generating DEVISE's controllers 
  devise_for :users, controllers: { sessions: 'users/sessions' }

    # - setting DEVISE's login/Register view as root
  devise_scope :user do 
    root to: "users/sessions#new"
  end

    # - soft delete
    # - user clicks check box at app/views/contacts/index
    # - User.deactivate toggled true/false
    # - User.deactivated = true 
    #   + displayed in side bar
  post '/deactivate_contact' => 'contacts#deactivate_contact'
  post '/reactivate_contact' => 'contacts#reactivate_contact'

    # - search box at: views/contacts/index.html.erb
    # - user types search string
    # - list of matching Contacts is displayed
  post 'search_contacts' => 'contacts#search_contacts'

end

app/models/contact.rb
class Contact < ApplicationRecord

  belongs_to :user

  validates :email, uniqueness: { case_sensitive: false, message: "email taken!" }
  validates :name, presence: true

    # - generates csv for user
    # - triggered in views/contact/index 
  def to_csv ops = {}
    
    cols = [ 'id', 'name', 'email', 'phone', 'address', 'company', 'birtday', 'deactivate' ]

    CSV.generate ops do |csv|
      csv << cols
      csv << attributes.values_at(*cols)
    end

  end # to_csv


    # - generates csv for all contacts
    # - link in views/contacts/index
  def self.to_csv ops = {}
    
    cols = [ 'id', 'name', 'email', 'phone', 'address', 'company', 'birtday', 'deactivate' ]

    CSV.generate ops do |csv|
      csv << cols
      
      all.each do |contact|
        csv << contact.attributes.values_at(*cols)
      end

    end

  end # self.to_csv  


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  require 'csv'

  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


# - pulls list of contacts dependend ont user signed in
# - pulls deactivated contatcs for separate displaying
# - @function 
#   + used in #index (here) and (search_contacts)
#   + #index is reused by #search_contacts for rendering results
#   + string rendered in <h1> at app/views/contacts/index.html.erb
# - responds with csv when pormpted by user 
  def index
    @contacts = Contact.where( "user_id = ? and deactivate = false", current_user.id ) || []    
    @deactivated_contacts = Contact.where( "user_id = ? and deactivate = true", current_user.id)
    @function = "Contacts"

    respond_to do |format| 

      format.html 
      format.csv { send_data Contact.to_csv }

    end

  end

    # - displays a contact 
    # - returns conrresponding csv 
  def show

    @contact = Contact.find params['id']
    
    respond_to do |format|    

      format.html 

      format.csv { send_data @contact.to_csv }

    end

  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


    # - gets called via POST (form) in app/views/contacts/index.html.erb
    #   + POST from multiple check_box_tag 
    # - goes through array params['hide'] of Contact id's
    # - sets Contact.deactivate to true 
  def deactivate_contact 

    to_hide = params['hide']
    go = redirect_to contacts_path

    if !to_hide
      go
    else

     to_hide.each do |i| 
       @contact_to_hide = Contact.find i
       @contact_to_hide.update deactivate: true
     end

     go

    end
  end

    # - gets called via POST (form) in app/views/_deactivated_contact.html.erb
    #   + POST from multiple check_box_tag 
    # - goes through array params['show'] of Contact id's
    # - sets Contact.deactivate to false     
  def reactivate_contact 
    
    to_show = params['show']
    go = redirect_to contacts_url

    if !to_show
      go 
    else
      
      to_show.each do |i|
        @contact_to_show = Contact.find i
        @contact_to_show.update deactivate: false
      end

    end

  end # reactivate_contact

    # - search box at: views/contacts/index.html.erb
    # - user types search string
    # - list of matching Contacts is displayed
    # - reuses #index and @contacts for rendering results
    # - @function
    # -   + rendered in <h1> at app/views/contacts/index.html.erb
  def search_contacts 

    search_term = params['search'][0]

    if search_term.length != 0

      @contacts = Contact.where "name = ?", search_term

      @function = "Search Results"

      render :index

    else
      redirect_to contacts_path
    end

  end  

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :address, :company, :birtday, :user_id, :format)
    end


end

app/helpers/contacts_helper.rb
module ContactsHelper

    # - to calculate age
    # - used in app/views/contacts/index
  def get_age(some_date)

    now = Date.today
    bday_this_year = Date.new now.year, some_date.month, some_date.day

    now.year - some_date.year - ( bday_this_year > now ? 1 : 0 )

  end

end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <br />
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <br />
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :company %>
    <br />
    <%= f.text_field :company %>
  </div>

  <div class="field">
    <%= f.label :birtday %>
    <br />
    <%= f.date_select :birtday, start_year: 1900, end_year: 2016 %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/contacts/edit.html.erb
<div class="row">

  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

  <div class="editContDiv">
  
    <h1 class="editContH1">Editing Contact</h1>

    <%= render 'form', contact: @contact %>

    <%= link_to 'Show', @contact %> |
    <%= link_to 'Back', contacts_path %>

  </div><!-- editContDiv -->

  </div><!-- cols -->

</div><!-- row -->

app/views/contacts/index.html.erb
<!-- 
###########
  - displays @contacts from contacts#index (all contacts)
  - uses app/helpers/contact_helper.rb returns converted birthdate to age

  Bootstrap
    - crates 1 main row
      + contacts
      + deactivated (sidebar)
##########
-->

<div class="row">

  <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10" >

    <div class="contactsListing">

      <h1 class="contIndxH1"><%= @function %></h1>

      <%= button_to 'New Contact', new_contact_path, method: 'get', class:'newContact' %>
      <%= button_to 'Csv All', contacts_path(format:'csv'), method: 'get', class: 'csvAll' %>

      <!-- 
    ################################
      - form for soft deletion 
      - takes a set of cliked boxex and sets ther db column 'soft_del' to true
      - POsts to contactsController#deactivate_contact
    ################################        
      -->    
        
      <%= form_tag deactivate_contact_path do  %>

      <%= submit_tag "Deactivate Checked", class: "deactivateSubmit" %>

       <div class="row">

        <% @contacts.each do |contact| %>
            <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3" >

              <div class="contacts">

                <p>
                  <span>Name:</span>
                  
                  <%= contact.name %>
                </p>
                <p>
                  <span>Email: </span>
                  
                  <%= contact.email %>
                </p>            
                <p>
                  <span>Phone: </span>
                  
                  <%= contact.phone %>
                </p>
                <p>
                  <span>Address: </span>
                  
                  <%= contact.address %>
                </p>
                <p>
                  <span>Age: </span>
                  
                  <%= get_age(contact.birtday) %>
                </p>

                <div class="editContact">
               
                  <p>
                  <%= link_to 'Show', contact %>|
                  <%= link_to 'Edit', edit_contact_path(contact) %>|
                  <%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %>|

<!-- - just a button for csv download 
     - also used at views/contacts/show
-->      
                  <%= render partial: 'shared/csv_button', locals: { id: contact.id } %>


                  </p>

          <!-- DISPLAYS BUTTON TO HIDE  -->        
                  <div class="hideBox">
                    <%= check_box_tag "hide[]", "#{contact.id}" %>
                    <%= label_tag "hide", "hide"  %> 
                  </div>

                </div> <!-- editContact -->

              </div><!-- .contacts -->

            </div> <!-- cols -->

          <% end %>

        </div> <!-- row -->

      <%= submit_tag "Deactivate Checked", class: "deactivateSubmit" %>

      <% end %>  <!-- form -->


      <br>

    </div><!-- contactsListing -->

      <%= button_to 'New Contact', new_contact_path, method: 'get', class:'newContact' %>

  </div><!-- cols  -->


  <div class="col-xs-12 col-sm-1 col-md-2 col-lg-2">

    <div class="contRestore">
     
      <h3 class="hiddenH3">Hidden</h3>

      <ul class="deactivatedUl"> 
      <!-- 
    ################################
      - form for restating a contact 
      - takes a set of cliked boxex and sets ther db column 'soft_del' to false
      - POsts to contactsController#reactivate_contact
    ################################        
      -->      
        <%= form_tag reactivate_contact_path do %>
          <%= render partial: 'shared/deactivated_contact', collection: @deactivated_contacts %>
          <br>
          <%= submit_tag 'Reactivate' %>
        <% end %>
      </ul>

    </div> <!-- contRestore -->

<!-- 
- rails search form 
- looks for a contact
- ContactsController#search_contact(name)

-->
    <div class="searchCont">

      <%= form_tag search_contacts_path do %>
        <%= label_tag "search" %>
        <br>
        <%= text_field_tag "search[]", nil, placeholder: 'search by name' %>
        <br>
        <%= submit_tag 'Search' %>
      <% end %>

    </div> <!-- searchCont -->


  </div> <!-- cols -->

</div> <!-- row -->

app/views/contacts/new.html.erb
<div class="row">

  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

  <div class="editContDiv">
  
    <h1 class="editContH1">New Contact</h1>

    <%= render 'form', contact: @contact %>

    <%= link_to 'Back', contacts_path %>

  </div><!-- editContDiv -->

  </div><!-- cols -->

</div><!-- row -->

app/views/contacts/show.html.erb
<div class="row">

  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <p id="notice"><%= notice %></p>

    <div class="userShow">

      <p>
        <span>Name:</span>
        
        <%= @contact.name %>
      </p>

      <p>
        <span>Email:</span>
        
        <%= @contact.email %>
      </p>

      <p>
        <span>Phone:</span>
        
        <%= @contact.phone %>
      </p>

      <p>
        <span>Address:</span>
        
        <%= @contact.address %>
      </p>

      <p>
        <span>Company:</span>
        
        <%= @contact.company %>
      </p>

      <p>
        <span>Birtday:</span>
        <%= @contact.birtday %>
      </p>

      <%= link_to 'Edit', edit_contact_path(@contact) %> |
      <%= link_to 'Back', contacts_path %> |

<!-- - just a button for csv download 
     - also used at views/contacts/index
-->      
      <%= render partial: 'shared/csv_button', locals: { id: @contact.id } %>

    </div><!-- userShow -->

  </div><!-- cols -->

</div><!-- row -->